### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by XuanPhat0603** [XuanPhat0603/Link#1]
class T002Logic {
    private T002Dao dao;
    private T002Form form;
    private PaginationSessionDto paginationSessionDto;
    private String errorMsg;
    private HttpServletRequest request;

    public void setForm(HttpServletRequest request, T002Form form) {
        this.request = request;
        this.form = form;
        this.paginationSessionDto = (PaginationSessionDto) request.getSession().getAttribute("pagination");
        this.dao = new T002Dao();
    }

    public boolean search() {
        // .....
        if (validate(form)) {
            return false;
        }

        return true;
    }

    public boolean validate(T002Form form) {
        // If there is no error, return true.
        if (form.getTxtName().isEmpty()) {
            form.setErrorMsg("Name is required");
            return false;
        }
        return true;
    }
}

**Comment by teddy6793** [comment]
<action 
        	path = "/T003"
        	type = "com.action.T003Action"
        	name = "T002Formbean"
        	validate = "true"
        	input = "/pages/T003.jsp">
        	<forward name = "addCustomer" path = "/pages/T003.jsp"></forward>
        	<forward name = "updateCustomer" path = "/pages/T003.jsp"></forward>
        </action>

public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		T002Formbean customer = (T002Formbean)form;
		String customerId = request.getParameter("customerID");		
		
		if (customerId == null || Constants.NONE.equals(customerId)) {
			customer.setCustomerID(0);
			request.setAttribute("customerEdit", customer);
			return mapping.findForward("addCustomer");
		}
		
		return mapping.findForward("updateCustomer");
	}

**Comment by teddy6793** [comment]
<action 
        	path = "/T003"
        	type = "com.action.T003Action"
        	name = "T002Formbean"
        	validate = "true"
        	input = "/pages/T003.jsp">
        	<forward name = "addCustomer" path = "/pages/T003.jsp"></forward>
        	<forward name = "updateCustomer" path = "/pages/T003.jsp"></forward>
        </action>
 //struts config

**Comment by teddy6793** [comment]
path = "/T003"
        	type = "com.action.T003Action"
        	name = "T002Formbean"
        	validate = "true"
        	input = "/pages/T003.jsp">
        	<forward name = "addCustomer" path = "/pages/T003.jsp"></forward>
        	<forward name = "updateCustomer" path = "/pages/T003.jsp"></forward>
